title: QD Knowledge
description: 老登快速复习C++低延迟技术栈，点到为止
author: 4thcalabash
baseurl: "/qd-knowledge"
url: "https://4thcalabash.github.io"

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

plugins:
  - jekyll-feed
  - jekyll-seo-tag
