title: QD Knowledge
description: QD Cheatsheet, not a Tutorial
author: 4thcalabash
baseurl: "/qd-knowledge"
url: "https://4thcalabash.github.io"

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 演示代码不参与站点构建
exclude:
  - _demo
